# Generated by Django 3.0.2 on 2020-02-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_auto_20200201_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loans.Loan'),
        ),
    ]
