# Generated by Django 3.0.2 on 2020-02-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0006_participants_hold_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='hold_amount',
        ),
    ]
