# Generated by Django 3.0.2 on 2020-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0007_remove_participants_hold_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='hold_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='profit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='totla_loan_amount',
            field=models.IntegerField(default=0),
        ),
    ]
